# Use a imagem oficial do Node.js como imagem base
FROM node:14-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Instale as dependências do projeto
COPY package*.json ./
RUN npm install

# Copie o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

# Exponha a porta 3030 para o contêiner
EXPOSE 3030

# Comando para iniciar o servidor de desenvolvimento do React
CMD ["npm", "start"]
